In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
df = pd.read_csv(os.path.join("PUF_FinalCSV.csv"))
df = df.fillna(0)
df.head()

,PUF_ID,final_weight,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,99047770,154338.590800,WEST,17,1,2,1.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,99055860,151.958306,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,99024610,9073.693224,WEST,17,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,99033910,1832.858493,WEST,17,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,99047930,10658.409400,WEST,17,1,2,4.0,1.0,2.0,1.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0

In [6]:
columns = []
for col in df.columns: 
    if col not in ['Q37_WEEKS_WORKED','PUF_ID','final_weight']:
        columns.append(col)

In [7]:
df['Q3_Q3_A_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_A_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_B_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_B_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_C_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_C_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_D_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_D_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_E_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_E_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})

#Q2_COL_CREDIT
df['Q2_COL_CREDIT']=df.Q2_COL_CREDIT.replace(to_replace={1.0:0})
df['Q2_COL_CREDIT']=df.Q2_COL_CREDIT.replace(to_replace={-3.0:0})

#Q5_COL_ENROLL
df['Q5_COL_ENROLL']=df.Q5_COL_ENROLL.replace(to_replace={1.0:0})

#Q9_CERT_LIC
df['Q9_CERT_LIC']=df.Q9_CERT_LIC.replace(to_replace={1.0:0})
df['Q9_CERT_LIC']=df.Q9_CERT_LIC.replace(to_replace={2.0:1})

In [8]:
df.head(25)

,PUF_ID,final_weight,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,99047770,154338.590800,WEST,17,1,2,0.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,99055860,151.958306,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,99024610,9073.693224,WEST,17,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,99033910,1832.858493,WEST,17,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,99047930,10658.409400,WEST,17,1,2,4.0,0.0,0.0,0.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0
5,99012060,117697.986200,WEST,17,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0
6,99023470,491.580789,WEST,16,1,2,2.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
7,99015240,1667.416233,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
8,99000930,10174.818860,WEST,16,1,2,4.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
9,99059680,4177.104315,WEST,17,1,2,4.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0
10,99018370,1950.559582,WEST,16,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
11,99025330,496.846955,WEST,16,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
12,99003400,95396.103130,WEST,17,1,3,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
13,99040880,9475.191299,WEST,17,1,3,3.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0
14,99012600,108.496670,MIDWEST,1,1,2,3.0,0.0,0.0,0.0,...,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
15,99050600,835.354083,WEST,16,1,2,4.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
16,99016580,248.423477,WEST,16,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
17,99025780,1522.569484,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
18,99010770,3936.385571,WEST,16,1,2,4.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
19,99008310,121.492578,WEST,16,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
20,99036800,83770.233530,WEST,20,1,2,4.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0
21,99031150,798.894052,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
22,99041780,1633.548667,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
23,99050680,6537.475263,MIDWEST,4,1,3,0.0,0.0,0.0,0.0,...,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
24,99038110,128708.146000,WEST,20,1,2,4.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0

In [9]:
data = df[columns]
data.head()

,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,Q3_Q3_D_R,Q3_Q3_E_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,WEST,17,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,WEST,17,1,1,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,WEST,17,1,2,3.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,WEST,17,1,2,4.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0

In [10]:
#data.columns = data.columns.astype('category')
for col in columns: 
    data[col]=pd.Categorical(data[col])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [11]:
data.head()

,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,Q3_Q3_D_R,Q3_Q3_E_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,WEST,17,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,WEST,17,1,1,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,WEST,17,1,2,3.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,WEST,17,1,2,4.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0

In [10]:
data.dtypes

REGION                   category
STRATUM1                 category
LANG                     category
Q1_HS                    category
Q2_COL_CREDIT            category
Q3_Q3_A_R                category
Q3_Q3_B_R                category
Q3_Q3_C_R                category
Q3_Q3_D_R                category
Q3_Q3_E_R                category
Q4_HIGHEST_EDU_FOS       category
Q5_COL_ENROLL            category
Q6_EDU_PLAN              category
Q7A                      category
Q7_B_DEGREE_PLAN_FOS     category
Q8_ESL                   category
Q9_CERT_LIC              category
Q10_NUM_ACTIVE           category
Q11_MOST_IMP_CERT_LIC    category
Q12_CERT_LIC_WORK        category
Q13_CERT_LIC_REQ         category
Q14_CERT_LIC_REV         category
Q15_Q15_A_R              category
Q15_Q15_B_R              category
Q15_Q15_C_R              category
Q15_D_SPECIFY_FLAG       category
Q16_CERT_LIC_CUR_JOB     category
Q17_A                    category
Q17_B                    category
Q17_C                    category
                           ...
Q29_Q29_C_R              category
Q29_Q29_D_R              category
Q29_Q29_E_R              category
Q30_APP_CERT_LIC         category
Q31_APP_CERTIFICATE      category
Q32_APP_JOB              category
Q33_APP_SKILL_USE        category
Q34_A                    category
Q34_B                    category
Q34_C                    category
Q35_EMPLOYED             category
Q36_FULL_TIME            category
Q37_WEEKS_WORKED         category
Q38_HOURS_WORKED         category
Q40_BUSINESS_TYPE        category
Q43_JOB_LIC              category
Q44_MILITARY             category
Q45_GENDER               category
Q46_MARITAL_STATUS       category
Q47_AGE                  category
Q48_HISPANIC             category
Q49_RACE_01              category
Q49_RACE_02              category
Q49_RACE_03              category
Q49_RACE_04              category
Q49_RACE_05              category
Q49_RACE_06              category
Q49_RACE_07              category
Q50_INTERNET             category
Q51_CITIZENSHIP          category
Length: 78, dtype: object

In [12]:
data = pd.get_dummies(data)

In [13]:
data.head()

,REGION_MIDWEST,REGION_NORTHEAST,REGION_SOUTH,REGION_WEST,STRATUM1_1,STRATUM1_2,STRATUM1_3,STRATUM1_4,STRATUM1_5,STRATUM1_6,...,Q49_RACE_07_1.0,Q50_INTERNET_-3.0,Q50_INTERNET_0.0,Q50_INTERNET_1.0,Q50_INTERNET_2.0,Q51_CITIZENSHIP_-3.0,Q51_CITIZENSHIP_0.0,Q51_CITIZENSHIP_1.0,Q51_CITIZENSHIP_2.0,Q51_CITIZENSHIP_3.0
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1,1,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [14]:
feature_names = data.columns

In [15]:
target = df["Q37_WEEKS_WORKED"]

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [17]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.5986137366099559

In [18]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.6843100189035917

In [19]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.05315190045608562, 'Q38_HOURS_WORKED_0.0'),
 (0.04780462094849973, 'Q40_BUSINESS_TYPE_0.0'),
 (0.0459432766710759, 'Q39_EARNINGS_0.0'),
 (0.04586951629478151, 'Q43_JOB_LIC_0.0'),
 (0.03446214404779446, 'Q36_FULL_TIME_2.0'),
 (0.02672158918598531, 'Q36_FULL_TIME_0.0'),
 (0.02592276359722541, 'Q35_EMPLOYED_1'),
 (0.024458433329071286, 'Q35_EMPLOYED_2'),
 (0.02284879802398204, 'Q43_JOB_LIC_1.0'),
 (0.0198776392548958, 'Q39_EARNINGS_1.0'),
 (0.013020625315954763, 'Q38_HOURS_WORKED_40.0'),
 (0.009816248486775737, 'Q36_FULL_TIME_1.0'),
 (0.009383772202849522, 'Q43_JOB_LIC_2.0'),
 (0.008590071802019346, 'Q39_EARNINGS_2.0'),
 (0.008467813720492694, 'Q40_BUSINESS_TYPE_6.0'),
 (0.006538759726839522, 'Q39_EARNINGS_8.0'),
 (0.0063301122614965065, 'Q46_MARITAL_STATUS_1'),
 (0.0062975050373438824, 'Q46_MARITAL_STATUS_5'),
 (0.006088160765108047, 'Q40_BUSINESS_TYPE_8.0'),
 (0.00581285014472867, 'Q45_GENDER_1'),
 (0.005758930936999012, 'Q2_COL_CREDIT_4.0'),
 (0.005667327038104761, 'Q39_EARNINGS_3.0'),
 (0.005645801688056916, 'Q45_GENDER_2'),
 (0.005583694152793631, 'Q18_A_2'),
 (0.005559214266274066, 'Q49_RACE_01_0.0'),
 (0.005444511026333267, 'Q49_RACE_01_1.0'),
 (0.005402703534041662, 'Q18_A_1'),
 (0.00530733808521223, 'REGION_MIDWEST'),
 (0.0050148219615922, 'REGION_NORTHEAST'),
 (0.00476967923267861, 'Q2_COL_CREDIT_0.0'),
 (0.0046927894447475835, 'Q39_EARNINGS_4.0'),
 (0.004661113410882711, 'REGION_WEST'),
 (0.004448881166680468, 'Q51_CITIZENSHIP_1.0'),
 (0.0044327905184340785, 'REGION_SOUTH'),
 (0.0044321032577769185, 'Q4_HIGHEST_EDU_FOS_0.0'),
 (0.0042214518937417535, 'Q48_HISPANIC_2'),
 (0.004106220793303372, 'Q48_HISPANIC_1'),
 (0.003969539386361854, 'Q1_HS_2'),
 (0.0038308383296688053, 'Q40_BUSINESS_TYPE_16.0'),
 (0.003774368977780324, 'Q40_BUSINESS_TYPE_1.0'),
 (0.003757084760549569, 'STRATUM1_2'),
 (0.003690996400934444, 'Q18_C_1'),
 (0.0036666052976054154, 'Q39_EARNINGS_5.0'),
 (0.0036241614672724025, 'Q49_RACE_02_1.0'),
 (0.0036209382542167433, 'Q49_RACE_02_0.0'),
 (0.003615434393852533, 'Q8_ESL_1'),
 (0.003594630979031359, 'Q51_CITIZENSHIP_2.0'),
 (0.003584272741918686, 'Q8_ESL_2'),
 (0.0035705549842559403, 'Q49_RACE_04_1.0'),
 (0.0035357450945209925, 'Q18_C_2'),
 (0.003535211831295049, 'Q39_EARNINGS_7.0'),
 (0.003503167750503002, 'Q38_HOURS_WORKED_20.0'),
 (0.003451206568844995, 'Q49_RACE_04_0.0'),
 (0.003347879577138835, 'STRATUM1_9'),
 (0.0033357494639962414, 'Q2_COL_CREDIT_3.0'),
 (0.003324325362378228, 'Q46_MARITAL_STATUS_3'),
 (0.003214262223097713, 'Q51_CITIZENSHIP_3.0'),
 (0.003184072440898742, 'Q38_HOURS_WORKED_35.0'),
 (0.0031542793786438145, 'Q50_INTERNET_2.0'),
 (0.003136129041580984, 'Q16_CERT_LIC_CUR_JOB_3.0'),
 (0.003109705419388672, 'Q38_HOURS_WORKED_30.0'),
 (0.0030897875487640673, 'Q49_RACE_06_1.0'),
 (0.003086890527116264, 'Q50_INTERNET_1.0'),
 (0.003046411428113866, 'Q49_RACE_06_0.0'),
 (0.0030271805980321637, 'Q4_HIGHEST_EDU_FOS_11.0'),
 (0.0030169128868071447, 'Q38_HOURS_WORKED_50.0'),
 (0.0029446566305162576, 'STRATUM1_7'),
 (0.0029353848957229993, 'STRATUM1_12'),
 (0.0028676458935529693, 'Q4_HIGHEST_EDU_FOS_6.0'),
 (0.0028639300832995805, 'Q5_COL_ENROLL_3'),
 (0.0028437630870109826, 'Q49_RACE_03_0.0'),
 (0.0028159754455943874, 'Q12_CERT_LIC_WORK_6.0'),
 (0.0027734030756869322, 'Q5_COL_ENROLL_0'),
 (0.002770403496526388, 'Q38_HOURS_WORKED_45.0'),
 (0.0027639227026095216, 'Q11_MOST_IMP_CERT_LIC_7.0'),
 (0.002701990178527101, 'Q4_HIGHEST_EDU_FOS_15.0'),
 (0.00268057457180565, 'Q39_EARNINGS_6.0'),
 (0.002653962981767231, 'Q2_COL_CREDIT_2.0'),
 (0.002649489674162757, 'Q40_BUSINESS_TYPE_13.0'),
 (0.0026188507547481366, 'STRATUM1_1'),
 (0.002602326776428251, 'Q47_AGE_22'),
 (0.0025908605469295637, 'Q49_RACE_03_1.0'),
 (0.002558020908026636, 'Q16_CERT_LIC_CUR_JOB_1.0'),
 (0.002537259316548738, 'STRATUM1_18'),
 (0.0024822286354290314, 'Q1_HS_3'),
 (0.002480699247945422, 'STRATUM1_17'),
 (0.0024469557610782722, 'Q40_BUSINESS_TYPE_20.0'),
 (0.002428397429530011, 'Q6_EDU_PLAN_0.0'),
 (0.002390236768638979, 'Q38_HOURS_WORKED_25.0'),
 (0.002375776167565552, 'Q6_EDU_PLAN_2.0'),
 (0.002295085121918353, 'Q4_HIGHEST_EDU_FOS_21.0'),
 (0.00228435245092088, 'Q4_HIGHEST_EDU_FOS_14.0'),
 (0.0022789374267989377, 'Q40_BUSINESS_TYPE_9.0'),
 (0.002233810396964437, 'Q47_AGE_24'),
 (0.002223513921223783, 'Q17_C_3.0'),
 (0.002221888949227823, 'Q1_HS_1'),
 (0.0022144233614232196, 'Q40_BUSINESS_TYPE_14.0'),
 (0.0022134109984129897, 'Q4_HIGHEST_EDU_FOS_8.0'),
 (0.0022092781400760695, 'Q4_HIGHEST_EDU_FOS_1.0'),
 (0.002205087273502998, 'Q7_B_DEGREE_PLAN_FOS_0.0'),
 (0.0021426197857717065, 'Q47_AGE_23'),
 (0.0021383118879365003, 'Q10_NUM_ACTIVE_1.0'),
 (0.0021301912588038534, 'Q40_BUSINESS_TYPE_4.0'),
 (0.0021189037878036154, 'Q4_HIGHEST_EDU_FOS_22.0'),
 (0.0020672954828314435, 'Q40_BUSINESS_TYPE_7.0'),
 (0.0020115615385731807, 'Q7A_0.0'),
 (0.002011408711191454, 'STRATUM1_14'),
 (0.001977307063062682, 'STRATUM1_19'),
 (0.001961214756388637, 'STRATUM1_6'),
 (0.0019545458843060427, 'Q47_AGE_28'),
 (0.0019371997251472655, 'Q40_BUSINESS_TYPE_17.0'),
 (0.0019336618596772115, 'Q38_HOURS_WORKED_15.0'),
 (0.0019294344931352582, 'Q4_HIGHEST_EDU_FOS_2.0'),
 (0.0019098954091198205, 'STRATUM1_4'),
 (0.0019028486603668599, 'Q15_Q15_C_R_1.0'),
 (0.0018890389179133363, 'Q40_BUSINESS_TYPE_10.0'),
 (0.0018744637716400503, 'STRATUM1_16'),
 (0.0018663435799198792, 'Q39_EARNINGS_9.0'),
 (0.0018439236019403469, 'Q15_Q15_C_R_2.0'),
 (0.0018411860382160636, 'Q4_HIGHEST_EDU_FOS_23.0'),
 (0.0018213261381828624, 'Q4_HIGHEST_EDU_FOS_12.0'),
 (0.0018188617826298836, 'Q17_D_3.0'),
 (0.0017996432229742045, 'Q7A_3.0'),
 (0.0017818728824346354, 'STRATUM1_11'),
 (0.0017685263526812586, 'Q27_APP_2'),
 (0.0017668780731719363, 'Q15_Q15_A_R_2.0'),
 (0.0017464426418297228, 'Q4_HIGHEST_EDU_FOS_18.0'),
 (0.0017297981707369734, 'Q47_AGE_35'),
 (0.001723345434086727, 'Q5_COL_ENROLL_2'),
 (0.0017214029866988057, 'Q14_CERT_LIC_REV_2.0'),
 (0.0017212255220172782, 'Q15_Q15_B_R_2.0'),
 (0.0017067763661678817, 'Q47_AGE_27'),
 (0.0016910294437658924, 'Q15_Q15_B_R_1.0'),
 (0.0016731381440666076, 'STRATUM1_8'),
 (0.00164992522766502, 'Q47_AGE_53'),
 (0.001614574331588888, 'Q47_AGE_25'),
 (0.0016133313956780604, 'Q17_A_0.0'),
 (0.001606121140229697, 'Q17_B_3.0'),
 (0.0015926727436865256, 'Q15_Q15_A_R_1.0'),
 (0.0015704325254024367, 'Q44_MILITARY_1'),
 (0.0015356297064761134, 'Q17_D_2.0'),
 (0.0015216684054468771, 'Q27_APP_1'),
 (0.0015075371144451235, 'Q10_NUM_ACTIVE_2.0'),
 (0.0015054252800789352, 'Q47_AGE_32'),
 (0.0015034031569473522, 'Q40_BUSINESS_TYPE_12.0'),
 (0.0014811024235769174, 'Q13_CERT_LIC_REQ_2.0'),
 (0.0014802896684770986, 'Q47_AGE_26'),
 (0.001459388714992664, 'Q47_AGE_55'),
 (0.0014554367955538481, 'Q47_AGE_33'),
 (0.0014534266991959358, 'Q47_AGE_21'),
 (0.0014474653044314447, 'Q47_AGE_64'),
 (0.0014451565644113978, 'STRATUM1_13'),
 (0.0014409677276473378, 'Q38_HOURS_WORKED_10.0'),
 (0.001412407057974128, 'Q47_AGE_45'),
 (0.0014085863078114346, 'Q47_AGE_30'),
 (0.0013925583163211363, 'Q47_AGE_50'),
 (0.0013788273390106117, 'Q47_AGE_61'),
 (0.0013705078407840984, 'Q12_CERT_LIC_WORK_8.0'),
 (0.001361008391978584, 'Q38_HOURS_WORKED_60.0'),
 (0.0013551121327211736, 'Q47_AGE_36'),
 (0.0013361282997581105, 'Q7_B_DEGREE_PLAN_FOS_15.0'),
 (0.0013340819986121988, 'Q47_AGE_51'),
 (0.001312685726026529, 'STRATUM1_3'),
 (0.0013051051836763142, 'Q47_AGE_29'),
 (0.0013009402848121118, 'Q47_AGE_34'),
 (0.0012850325334535912, 'Q38_HOURS_WORKED_24.0'),
 (0.0012806339447013488, 'Q44_MILITARY_4'),
 (0.0012781090143550603, 'Q47_AGE_31'),
 (0.001275341681743257, 'Q25_CERTIFICATE_JOB_1.0'),
 (0.001269828069891145, 'Q47_AGE_57'),
 (0.0012605212044581632, 'Q47_AGE_43'),
 (0.0012601433909185623, 'Q47_AGE_18'),
 (0.001251410831310948, 'Q17_A_3.0'),
 (0.0012405806185485048, 'Q47_AGE_39'),
 (0.001233075721514167, 'Q7A_4.0'),
 (0.0012317377535017173, 'Q47_AGE_20'),
 (0.0012221181290201402, 'Q47_AGE_48'),
 (0.0012187578376799128, 'Q46_MARITAL_STATUS_2'),
 (0.0012164512196491516, 'Q40_BUSINESS_TYPE_2.0'),
 (0.0012104484727923563, 'Q15_Q15_B_R_0.0'),
 (0.0012022951847411823, 'Q47_AGE_56'),
 (0.001193869811209768, 'Q4_HIGHEST_EDU_FOS_19.0'),
 (0.0011862558404349647, 'Q47_AGE_63'),
 (0.001185679747366493, 'Q17_D_1.0'),
 (0.0011588244994967917, 'Q47_AGE_19'),
 (0.0011471085027938595, 'Q15_Q15_A_R_0.0'),
 (0.0011449084832054924, 'Q46_MARITAL_STATUS_4'),
 (0.0011427951172033727, 'Q47_AGE_62'),
 (0.001135109878029496, 'Q47_AGE_60'),
 (0.0011246148303471508, 'Q14_CERT_LIC_REV_3.0'),
 (0.0011099416422363478, 'Q23_CERTIFCATE_CREDITS_2.0'),
 (0.001109354755105594, 'Q4_HIGHEST_EDU_FOS_7.0'),
 (0.0010974656947935393, 'Q40_BUSINESS_TYPE_3.0'),
 (0.0010891140869992647, 'Q18_D_SPECIFY_0.0'),
 (0.001083804942623181, 'Q17_C_2.0'),
 (0.001081010587270652, 'Q17_C_0.0'),
 (0.0010679819407763812, 'Q22_CERTIFICATE_ENROLL_3.0'),
 (0.0010616075431719675, 'Q38_HOURS_WORKED_32.0'),
 (0.001053542671072525, 'Q18_D_SPECIFY_1.0'),
 (0.001043437004646981, 'Q26_A_0.0'),
 (0.0010365387143863125, 'Q18_D_1'),
 (0.0010334784756451567, 'Q47_AGE_47'),
 (0.0010199122917314743, 'Q38_HOURS_WORKED_5.0'),
 (0.00101865459632979, 'Q24_CERTIFICATE_TRAIN_2.0'),
 (0.0010081958725900685, 'Q23_CERTIFCATE_CREDITS_0.0'),
 (0.0010081755351867975, 'Q11_MOST_IMP_CERT_LIC_1.0'),
 (0.0010063210437064938, 'Q40_BUSINESS_TYPE_5.0'),
 (0.0010059173127185581, 'Q18_D_2'),
 (0.0010034337951265507, 'Q26_B_1.0'),
 (0.0010016793975089933, 'Q26_A_2.0'),
 (0.0010015600773796989, 'Q47_AGE_37'),
 (0.0010008574043689593, 'Q38_HOURS_WORKED_8.0'),
 (0.000989960651524053, 'Q47_AGE_40'),
 (0.000979421150078044, 'Q14_CERT_LIC_REV_1.0'),
 (0.000971609709603562, 'Q16_CERT_LIC_CUR_JOB_2.0'),
 (0.0009691076805498347, 'Q24_CERTIFICATE_TRAIN_0.0'),
 (0.000966447515859749, 'LANG_1'),
 (0.0009660540300737912, 'Q38_HOURS_WORKED_38.0'),
 (0.0009640442290599478, 'Q26_B_0.0'),
 (0.0009626020495195821, 'Q26_A_3.0'),
 (0.0009608735911780672, 'Q47_AGE_52'),
 (0.0009599109546220619, 'LANG_2'),
 (0.0009563735680642592, 'Q11_MOST_IMP_CERT_LIC_5.0'),
 (0.0009557969111560479, 'Q22_CERTIFICATE_ENROLL_0.0'),
 (0.0009498960355738376, 'Q38_HOURS_WORKED_12.0'),
 (0.0009433468816090599, 'Q10_NUM_ACTIVE_0.0'),
 (0.000937109344480163, 'Q15_Q15_C_R_0.0'),
 (0.0009298835341508306, 'Q26_C_0.0'),
 (0.0009282554598579342, 'Q47_AGE_46'),
 (0.0009243858060332469, 'Q21_CERTIFICATE_HOURS_1.0'),
 (0.0009216438922954683, 'Q25_CERTIFICATE_JOB_2.0'),
 (0.0009142565009013872, 'Q47_AGE_44'),
 (0.0009104830266313427, 'Q16_CERT_LIC_CUR_JOB_0.0'),
 (0.0009104056568469925, 'Q21_CERTIFICATE_HOURS_0.0'),
 (0.0009092457589005283, 'Q47_AGE_42'),
 (0.0009081881721554956, 'Q17_B_2.0'),
 (0.0009058321009621528, 'Q26_C_3.0'),
 (0.0009021131517822401, 'Q47_AGE_58'),
 (0.0009017986706436057, 'Q47_AGE_54'),
 (0.0009009758076997097, 'Q10_NUM_ACTIVE_3.0'),
 (0.0008982498366776853, 'Q25_CERTIFICATE_JOB_0.0'),
 (0.0008967045637452087, 'Q19_CERTIFICATE_FOS_0.0'),
 (0.0008914035391470668, 'Q11_MOST_IMP_CERT_LIC_0.0'),
 (0.0008899920807679395, 'Q17_A_2.0'),
 (0.0008886708100006501, 'Q25_CERTIFICATE_JOB_4.0'),
 (0.000883790598931232, 'Q4_HIGHEST_EDU_FOS_16.0'),
 (0.0008724375878072517, 'Q17_D_0.0'),
 (0.0008716698836876507, 'Q17_B_0.0'),
 (0.0008696043309549147, 'Q26_C_2.0'),
 (0.0008678766031838857, 'Q19_CERTIFICATE_FOS_14.0'),
 (0.0008586338204711534, 'Q12_CERT_LIC_WORK_0.0'),
 (0.000857551791306127, 'Q13_CERT_LIC_REQ_1.0'),
 (0.0008571110019396763, 'Q32_APP_JOB_1.0'),
 (0.000855545242612818, 'Q13_CERT_LIC_REQ_0.0'),
 (0.0008554782638491958, 'Q47_AGE_49'),
 (0.0008538510835867404, 'Q38_HOURS_WORKED_48.0'),
 (0.0008469424679671491, 'Q7_B_DEGREE_PLAN_FOS_21.0'),
 (0.0008368433873888714, 'Q23_CERTIFCATE_CREDITS_1.0'),
 (0.0008340504466174929, 'Q7A_2.0'),
 (0.0008338982357531834, 'Q25_CERTIFICATE_JOB_3.0'),
 (0.0008256986549018831, 'Q4_HIGHEST_EDU_FOS_5.0'),
 (0.0008256712568497214, 'Q26_B_3.0'),
 (0.0008209645298506994, 'Q29_Q29_E_R_2.0'),
 (0.0008207084496816168, 'Q14_CERT_LIC_REV_0.0'),
 (0.0008177753700006718, 'Q38_HOURS_WORKED_37.0'),
 (0.0007924210399174755, 'Q29_Q29_A_R_2.0'),
 (0.0007919253459557875, 'Q47_AGE_38'),
 (0.0007862502630472534, 'Q38_HOURS_WORKED_36.0'),
 (0.0007855793266452042, 'Q18_D_SPECIFY_2.0'),
 (0.000782462348457829, 'Q38_HOURS_WORKED_16.0'),
 (0.0007583686675044335, 'Q24_CERTIFICATE_TRAIN_1.0'),
 (0.000744216226995881, 'Q11_MOST_IMP_CERT_LIC_9.0'),
 (0.0007427175842601633, 'Q34_A_3.0'),
 (0.000742614783437357, 'Q33_APP_SKILL_USE_1.0'),
 (0.0007391288353611951, 'Q21_CERTIFICATE_HOURS_4.0'),
 (0.0007384689834425439, 'Q29_Q29_B_R_1.0'),
 (0.0007381183819648915, 'Q47_AGE_59'),
 (0.000735809034349443, 'Q31_APP_CERTIFICATE_2.0'),
 (0.000728878903840706, 'Q31_APP_CERTIFICATE_1.0'),
 (0.0007228231973047597, 'Q7A_1.0'),
 (0.0007186436099242833, 'Q34_B_0.0'),
 (0.0007172418142790746, 'Q38_HOURS_WORKED_42.0'),
 (0.0007152001392310818, 'Q28_APP_WORK_6.0'),
 (0.0007137548275469973, 'Q6_EDU_PLAN_1.0'),
 (0.000712377921270403, 'Q7A_6.0'),
 (0.0007067267213536264, 'Q29_Q29_C_R_1.0'),
 (0.0006951067985270489, 'Q27_APP_3'),
 (0.0006922574456798527, 'Q34_C_3.0'),
 (0.0006919521687997941, 'Q30_APP_CERT_LIC_1.0'),
 (0.0006871030206160915, 'Q7_B_DEGREE_PLAN_FOS_6.0'),
 (0.0006832389339041493, 'Q34_B_3.0'),
 (0.0006758643699565805, 'Q29_Q29_C_R_0.0'),
 (0.0006639869784997695, 'Q34_A_0.0'),
 (0.0006605650885442121, 'Q33_APP_SKILL_USE_3.0'),
 (0.0006604168486384988, 'Q4_HIGHEST_EDU_FOS_17.0'),
 (0.0006573457641210135, 'Q7_B_DEGREE_PLAN_FOS_11.0'),
 (0.0006531025344624263, 'Q26_A_1.0'),
 (0.0006509142829621221, 'Q33_APP_SKILL_USE_0.0'),
 (0.0006497559189303642, 'Q32_APP_JOB_0.0'),
 (0.0006452969863184914, 'Q31_APP_CERTIFICATE_0.0'),
 (0.000645196166592784, 'Q26_B_2.0'),
 (0.0006419496337080457, 'Q38_HOURS_WORKED_9.0'),
 (0.0006328807266072717, 'Q33_APP_SKILL_USE_4.0'),
 (0.0006321113085373387, 'Q38_HOURS_WORKED_4.0'),
 (0.0006306207960901423, 'Q47_AGE_41'),
 (0.000629226099225388, 'Q29_Q29_A_R_0.0'),
 (0.0006246113249559727, 'Q4_HIGHEST_EDU_FOS_13.0'),
 (0.0006236770205917067, 'Q29_Q29_D_R_1.0'),
 (0.0006214101245620104, 'Q40_BUSINESS_TYPE_15.0'),
 (0.0006202718826663503, 'Q34_C_0.0'),
 (0.0006177984312144643, 'Q29_Q29_E_R_0.0'),
 (0.0006173999525729016, 'Q30_APP_CERT_LIC_0.0'),
 (0.0006167083052874367, 'Q29_Q29_B_R_2.0'),
 (0.0006149501961358204, 'Q29_Q29_D_R_0.0'),
 (0.00060948539252689, 'Q12_CERT_LIC_WORK_13.0'),
 (0.0006067886788049502, 'Q38_HOURS_WORKED_70.0'),
 (0.000605487246912427, 'Q32_APP_JOB_3.0'),
 (0.0006040959781699077, 'Q38_HOURS_WORKED_28.0'),
 (0.0005947006746324201, 'Q22_CERTIFICATE_ENROLL_4.0'),
 (0.0005884296345544713, 'Q28_APP_WORK_0.0'),
 (0.0005835751750457044, 'Q44_MILITARY_2'),
 (0.0005741864743016889, 'Q30_APP_CERT_LIC_2.0'),
 (0.000573379303342303, 'Q29_Q29_B_R_0.0'),
 (0.0005659012985686225, 'Q21_CERTIFICATE_HOURS_3.0'),
 (0.0005640767989004646, 'Q26_C_1.0'),
 (0.0005619130506688864, 'Q7_B_DEGREE_PLAN_FOS_23.0'),
 (0.0005592107053368576, 'Q49_RACE_05_1.0'),
 (0.0005554598718297079, 'Q12_CERT_LIC_WORK_9.0'),
 (0.0005516909642113593, 'Q32_APP_JOB_4.0'),
 (0.0005374536803423174, 'Q11_MOST_IMP_CERT_LIC_6.0'),
 (0.0005360484667734909, 'Q22_CERTIFICATE_ENROLL_2.0'),
 (0.0005316808336212404, 'Q49_RACE_05_0.0'),
 (0.0005246707779338627, 'Q34_B_1.0'),
 (0.0005214649349915095, 'Q34_C_2.0'),
 (0.0005209965674284375, 'Q7_B_DEGREE_PLAN_FOS_12.0'),
 (0.0005204896008706273, 'Q13_CERT_LIC_REQ_3.0'),
 (0.0005168038938670355, 'Q19_CERTIFICATE_FOS_10.0'),
 (0.0005153124931233005, 'Q21_CERTIFICATE_HOURS_2.0'),
 (0.000510486929438907, 'Q38_HOURS_WORKED_7.0'),
 (0.0005084389891781547, 'Q19_CERTIFICATE_FOS_12.0'),
 (0.0005078797767154269, 'Q4_HIGHEST_EDU_FOS_3.0'),
 (0.0005022329729586654, 'Q38_HOURS_WORKED_55.0'),
 (0.0005012668525968913, 'Q29_Q29_E_R_1.0'),
 (0.0005009157406607986, 'Q38_HOURS_WORKED_6.0'),
 (0.0004994781211583002, 'Q7_B_DEGREE_PLAN_FOS_2.0'),
 (0.0004990978727376783, 'Q38_HOURS_WORKED_65.0'),
 (0.0004982194885310804, 'Q10_NUM_ACTIVE_4.0'),
 (0.0004977610050158379, 'Q4_HIGHEST_EDU_FOS_9.0'),
 (0.0004974955374329798, 'Q32_APP_JOB_2.0'),
 (0.0004914337517784968, 'Q34_B_2.0'),
 (0.0004731727918145568, 'Q19_CERTIFICATE_FOS_5.0'),
 (0.0004687103276732438, 'Q29_Q29_A_R_1.0'),
 (0.0004663671400949169, 'Q38_HOURS_WORKED_43.0'),
 (0.0004651473787827867, 'Q12_CERT_LIC_WORK_7.0'),
 (0.00046365819589883707, 'STRATUM1_5'),
 (0.0004609166770999787, 'Q17_C_1.0'),
 (0.00046090033000768777, 'Q34_A_2.0'),
 (0.0004436579493485084, 'Q17_B_1.0'),
 (0.0004433201675152728, 'Q19_CERTIFICATE_FOS_6.0'),
 (0.00044171565907370015, 'Q4_HIGHEST_EDU_FOS_26.0'),
 (0.0004339175379949839, 'Q21_CERTIFICATE_HOURS_5.0'),
 (0.00043031125627689056, 'STRATUM1_20'),
 (0.0004285548598892965, 'Q4_HIGHEST_EDU_FOS_4.0'),
 (0.00042348573494487165, 'Q11_MOST_IMP_CERT_LIC_2.0'),
 (0.0004083281462199086, 'Q38_HOURS_WORKED_18.0'),
 (0.00040535468931943104, 'Q17_A_1.0'),
 (0.00040467217308432846, 'Q40_BUSINESS_TYPE_18.0'),
 (0.0004040682893398786, 'Q7_B_DEGREE_PLAN_FOS_22.0'),
 (0.00040265968946215825, 'Q29_Q29_C_R_2.0'),
 (0.0004022742991456465, 'Q7A_5.0'),
 (0.0004004406811487908, 'Q11_MOST_IMP_CERT_LIC_10.0'),
 (0.00038933964218976284, 'Q38_HOURS_WORKED_22.0'),
 (0.00038899506984295797, 'Q10_NUM_ACTIVE_5.0'),
 (0.00038744255151857733, 'STRATUM1_10'),
 (0.0003860438006412766, 'STRATUM1_15'),
 (0.000385758602806569, 'Q7_B_DEGREE_PLAN_FOS_8.0'),
 (0.00038181104429453724, 'Q9_CERT_LIC_0'),
 (0.0003738093543448261, 'Q29_Q29_D_R_2.0'),
 (0.0003734629822127132, 'Q7_B_DEGREE_PLAN_FOS_19.0'),
 (0.00035673127279930034, 'Q12_CERT_LIC_WORK_15.0'),
 (0.0003560417456173335, 'Q17_A_4.0'),
 (0.00035393455978306206, 'Q11_MOST_IMP_CERT_LIC_19.0'),
 (0.00034743071423125896, 'Q38_HOURS_WORKED_27.0'),
 (0.00034510113452390385, 'Q12_CERT_LIC_WORK_4.0'),
 (0.00034276388983848534, 'Q7_B_DEGREE_PLAN_FOS_24.0'),
 (0.0003377938631712292, 'Q17_C_4.0'),
 (0.00033630505998624006, 'Q4_HIGHEST_EDU_FOS_20.0'),
 (0.0003358882141718769, 'Q39_EARNINGS_-3.0'),
 (0.00033530764539843356, 'Q11_MOST_IMP_CERT_LIC_15.0'),
 (0.00033451389953864674, 'Q40_BUSINESS_TYPE_21.0'),
 (0.0003304641189105104, 'Q17_B_4.0'),
 (0.000329464583688391, 'Q28_APP_WORK_1.0'),
 (0.00032751060472641536, 'Q9_CERT_LIC_-3'),
 (0.0003182389311815431, 'Q12_CERT_LIC_WORK_1.0'),
 (0.00031455678669114855, 'Q33_APP_SKILL_USE_2.0'),
 (0.00031437068999326095, 'Q12_CERT_LIC_WORK_12.0'),
 (0.0003130387146624751, 'Q28_APP_WORK_2.0'),
 (0.00030916630550188636, 'Q18_A_-3'),
 (0.00030806922703563254, 'Q28_APP_WORK_4.0'),
 (0.0003039298655700385, 'Q28_APP_WORK_5.0'),
 (0.00030212091340351267, 'Q11_MOST_IMP_CERT_LIC_8.0'),
 (0.00029511756944310965, 'Q22_CERTIFICATE_ENROLL_1.0'),
 (0.0002871611770580523, 'Q40_BUSINESS_TYPE_19.0'),
 (0.00028681375866869625, 'Q18_C_-3'),
 (0.00028172221253843605, 'Q11_MOST_IMP_CERT_LIC_20.0'),
 (0.00027721113453409467, 'Q11_MOST_IMP_CERT_LIC_18.0'),
 (0.0002731658616877772, 'Q7_B_DEGREE_PLAN_FOS_14.0'),
 (0.00027113681005404907, 'Q8_ESL_-3'),
 (0.00026770970751571884, 'Q34_B_4.0'),
 (0.00025954378871156854, 'Q38_HOURS_WORKED_31.0'),
 (0.0002592505375775739, 'Q11_MOST_IMP_CERT_LIC_14.0'),
 (0.00025917157737280613, 'Q12_CERT_LIC_WORK_14.0'),
 (0.0002576179548733086, 'Q19_CERTIFICATE_FOS_2.0'),
 (0.0002574119648429662, 'Q18_D_-3'),
 (0.0002494636167622697, 'Q38_HOURS_WORKED_80.0'),
 (0.00024684972553668135, 'Q38_HOURS_WORKED_52.0'),
 (0.000244443980291909, 'Q40_BUSINESS_TYPE_11.0'),
 (0.00024201211804905894, 'Q38_HOURS_WORKED_2.0'),
 (0.0002411281434205097, 'Q18_D_SPECIFY_3.0'),
 (0.0002406150273032973, 'Q38_HOURS_WORKED_14.0'),
 (0.00023835074807570698, 'Q19_CERTIFICATE_FOS_8.0'),
 (0.00023689340398693438, 'Q38_HOURS_WORKED_19.0'),
 (0.0002361716488487445, 'Q38_HOURS_WORKED_44.0'),
 (0.00023357571406331198, 'Q26_B_4.0'),
 (0.00023037387950822186, 'Q11_MOST_IMP_CERT_LIC_16.0'),
 (0.00022806885854470373, 'Q21_CERTIFICATE_HOURS_-3.0'),
 (0.00022795709848689083, 'Q7_B_DEGREE_PLAN_FOS_17.0'),
 (0.00022788260139596482, 'Q12_CERT_LIC_WORK_2.0'),
 (0.0002262367202754937, 'Q34_A_1.0'),
 (0.00022509199021196173, 'Q11_MOST_IMP_CERT_LIC_12.0'),
 (0.00021982976748525902, 'Q11_MOST_IMP_CERT_LIC_4.0'),