In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
df = pd.read_csv(os.path.join("PUF_FinalCSV.csv"))
df = df.fillna(0)
df.head()

,PUF_ID,final_weight,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,99047770,154338.590800,WEST,17,1,2,1.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,99055860,151.958306,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,99024610,9073.693224,WEST,17,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,99033910,1832.858493,WEST,17,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,99047930,10658.409400,WEST,17,1,2,4.0,1.0,2.0,1.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0

In [3]:
columns = []
for col in df.columns: 
    if col not in ['Q39_EARNINGS','PUF_ID','final_weight']:
        columns.append(col)

In [4]:
df['Q3_Q3_A_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_A_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_B_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_B_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_C_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_C_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_D_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_D_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})
df['Q3_Q3_E_R']=df.Q3_Q3_A_R.replace(to_replace={1.0:0})
df['Q3_Q3_E_R']=df.Q3_Q3_A_R.replace(to_replace={2.0:1})

#Q2_COL_CREDIT
df['Q2_COL_CREDIT']=df.Q2_COL_CREDIT.replace(to_replace={1.0:0})
df['Q2_COL_CREDIT']=df.Q2_COL_CREDIT.replace(to_replace={-3.0:0})

#Q5_COL_ENROLL
df['Q5_COL_ENROLL']=df.Q5_COL_ENROLL.replace(to_replace={1.0:0})

#Q9_CERT_LIC
df['Q9_CERT_LIC']=df.Q9_CERT_LIC.replace(to_replace={1.0:0})
df['Q9_CERT_LIC']=df.Q9_CERT_LIC.replace(to_replace={2.0:1})

In [5]:
df.head(25)

,PUF_ID,final_weight,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,99047770,154338.590800,WEST,17,1,2,0.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,99055860,151.958306,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,99024610,9073.693224,WEST,17,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,99033910,1832.858493,WEST,17,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,99047930,10658.409400,WEST,17,1,2,4.0,0.0,0.0,0.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0
5,99012060,117697.986200,WEST,17,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0
6,99023470,491.580789,WEST,16,1,2,2.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
7,99015240,1667.416233,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
8,99000930,10174.818860,WEST,16,1,2,4.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
9,99059680,4177.104315,WEST,17,1,2,4.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0
10,99018370,1950.559582,WEST,16,1,1,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
11,99025330,496.846955,WEST,16,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
12,99003400,95396.103130,WEST,17,1,3,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
13,99040880,9475.191299,WEST,17,1,3,3.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0
14,99012600,108.496670,MIDWEST,1,1,2,3.0,0.0,0.0,0.0,...,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
15,99050600,835.354083,WEST,16,1,2,4.0,1.0,1.0,1.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
16,99016580,248.423477,WEST,16,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
17,99025780,1522.569484,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
18,99010770,3936.385571,WEST,16,1,2,4.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
19,99008310,121.492578,WEST,16,1,2,3.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
20,99036800,83770.233530,WEST,20,1,2,4.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0
21,99031150,798.894052,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0
22,99041780,1633.548667,WEST,16,1,2,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
23,99050680,6537.475263,MIDWEST,4,1,3,0.0,0.0,0.0,0.0,...,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
24,99038110,128708.146000,WEST,20,1,2,4.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0

In [6]:
#data = df.drop(['PUF_ID',"Q39_EARNINGS"], axis = 1)
#data = df.drop(['Q35_EMPLOYED','Q36_FULL_TIME','Q43_JOB_LIC','Q40_BUSINESS_TYPE','PUF_ID','final_weight','STRATUM1','LANG','Q39_EARNINGS','Q49_RACE_07','Q15_D_SPECIFY_FLAG','Q34_A','Q30_APP_CERT_LIC','Q31_APP_CERTIFICATE','Q34_C', 'Q29_Q29_B_R','Q29_Q29_C_R','Q29_Q29_E_R', 'Q29_Q29_A_R', 'Q38_HOURS_WORKED','Q29_Q29_D_R','Q9_CERT_LIC','Q37_WEEKS_WORKED','Q49_RACE_05', 'Q15_D_SPECIFY_FLAG'], axis=1)

In [ ]:
#columns = ["Q3_Q3_A_R","Q3_Q3_B_R","Q3_Q3_C_R","Q3_Q3_D_R","Q3_Q3_E_R","Q4_HIGHEST_EDU_FOS","Q9_CERT_LIC","Q45_GENDER","Q47_AGE","Q46_MARITAL_STATUS"]

In [7]:
data = df[columns]
data.head()

,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,Q3_Q3_D_R,Q3_Q3_E_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,WEST,17,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,WEST,17,1,1,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,WEST,17,1,2,3.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,WEST,17,1,2,4.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0

In [8]:
#data.columns = data.columns.astype('category')
for col in columns: 
    data[col]=pd.Categorical(data[col])

/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [9]:
data.head()

,REGION,STRATUM1,LANG,Q1_HS,Q2_COL_CREDIT,Q3_Q3_A_R,Q3_Q3_B_R,Q3_Q3_C_R,Q3_Q3_D_R,Q3_Q3_E_R,...,Q48_HISPANIC,Q49_RACE_01,Q49_RACE_02,Q49_RACE_03,Q49_RACE_04,Q49_RACE_05,Q49_RACE_06,Q49_RACE_07,Q50_INTERNET,Q51_CITIZENSHIP
0,WEST,17,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
1,MIDWEST,1,1,3,2.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
2,WEST,17,1,1,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,WEST,17,1,2,3.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0
4,WEST,17,1,2,4.0,0.0,0.0,0.0,0.0,0.0,...,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0

In [10]:
data.dtypes

REGION                   category
STRATUM1                 category
LANG                     category
Q1_HS                    category
Q2_COL_CREDIT            category
Q3_Q3_A_R                category
Q3_Q3_B_R                category
Q3_Q3_C_R                category
Q3_Q3_D_R                category
Q3_Q3_E_R                category
Q4_HIGHEST_EDU_FOS       category
Q5_COL_ENROLL            category
Q6_EDU_PLAN              category
Q7A                      category
Q7_B_DEGREE_PLAN_FOS     category
Q8_ESL                   category
Q9_CERT_LIC              category
Q10_NUM_ACTIVE           category
Q11_MOST_IMP_CERT_LIC    category
Q12_CERT_LIC_WORK        category
Q13_CERT_LIC_REQ         category
Q14_CERT_LIC_REV         category
Q15_Q15_A_R              category
Q15_Q15_B_R              category
Q15_Q15_C_R              category
Q15_D_SPECIFY_FLAG       category
Q16_CERT_LIC_CUR_JOB     category
Q17_A                    category
Q17_B                    category
Q17_C                    category
                           ...
Q29_Q29_C_R              category
Q29_Q29_D_R              category
Q29_Q29_E_R              category
Q30_APP_CERT_LIC         category
Q31_APP_CERTIFICATE      category
Q32_APP_JOB              category
Q33_APP_SKILL_USE        category
Q34_A                    category
Q34_B                    category
Q34_C                    category
Q35_EMPLOYED             category
Q36_FULL_TIME            category
Q37_WEEKS_WORKED         category
Q38_HOURS_WORKED         category
Q40_BUSINESS_TYPE        category
Q43_JOB_LIC              category
Q44_MILITARY             category
Q45_GENDER               category
Q46_MARITAL_STATUS       category
Q47_AGE                  category
Q48_HISPANIC             category
Q49_RACE_01              category
Q49_RACE_02              category
Q49_RACE_03              category
Q49_RACE_04              category
Q49_RACE_05              category
Q49_RACE_06              category
Q49_RACE_07              category
Q50_INTERNET             category
Q51_CITIZENSHIP          category
Length: 78, dtype: object

In [11]:
data = pd.get_dummies(data)

In [12]:
data.head()

,REGION_MIDWEST,REGION_NORTHEAST,REGION_SOUTH,REGION_WEST,STRATUM1_1,STRATUM1_2,STRATUM1_3,STRATUM1_4,STRATUM1_5,STRATUM1_6,...,Q49_RACE_07_1.0,Q50_INTERNET_-3.0,Q50_INTERNET_0.0,Q50_INTERNET_1.0,Q50_INTERNET_2.0,Q51_CITIZENSHIP_-3.0,Q51_CITIZENSHIP_0.0,Q51_CITIZENSHIP_1.0,Q51_CITIZENSHIP_2.0,Q51_CITIZENSHIP_3.0
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1,1,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [13]:
feature_names = data.columns

In [14]:
target = df["Q39_EARNINGS"]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [16]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.43163201008191554

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.49968494013862635

In [18]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.046749840221221015, 'Q37_WEEKS_WORKED_7'),
 (0.043256630387833506, 'Q38_HOURS_WORKED_0.0'),
 (0.03682392757977543, 'Q43_JOB_LIC_0.0'),
 (0.027296471352271996, 'Q40_BUSINESS_TYPE_0.0'),
 (0.017814046421964623, 'Q43_JOB_LIC_1.0'),
 (0.0175274760922474, 'Q36_FULL_TIME_2.0'),
 (0.015427320816197633, 'Q37_WEEKS_WORKED_1'),
 (0.014232062062106001, 'Q36_FULL_TIME_0.0'),
 (0.013948698863848108, 'Q38_HOURS_WORKED_40.0'),
 (0.013529258400988389, 'Q35_EMPLOYED_2'),
 (0.011955072430861226, 'Q35_EMPLOYED_1'),
 (0.011746524740204337, 'Q2_COL_CREDIT_4.0'),
 (0.010285420179935001, 'Q37_WEEKS_WORKED_6'),
 (0.008254446935255589, 'Q46_MARITAL_STATUS_1'),
 (0.008104238081469569, 'Q46_MARITAL_STATUS_5'),
 (0.00791521982102192, 'Q18_A_1'),
 (0.0077644416547389015, 'Q18_A_2'),
 (0.007454749985548074, 'Q36_FULL_TIME_1.0'),
 (0.0071163526080984425, 'Q45_GENDER_2'),
 (0.007064267805077997, 'REGION_MIDWEST'),
 (0.007027132757753999, 'Q45_GENDER_1'),
 (0.006886535693928569, 'Q40_BUSINESS_TYPE_8.0'),
 (0.006755777856073569, 'Q49_RACE_01_0.0'),
 (0.006735456495964766, 'Q43_JOB_LIC_2.0'),
 (0.006603976456003369, 'REGION_NORTHEAST'),
 (0.006462922003166962, 'Q40_BUSINESS_TYPE_6.0'),
 (0.0064088017687553185, 'REGION_WEST'),
 (0.00634474159352177, 'Q49_RACE_01_1.0'),
 (0.006151186920169579, 'REGION_SOUTH'),
 (0.005754860284597384, 'Q37_WEEKS_WORKED_3'),
 (0.005316273268092408, 'Q51_CITIZENSHIP_1.0'),
 (0.0052561505456930144, 'STRATUM1_2'),
 (0.005122601140356211, 'Q4_HIGHEST_EDU_FOS_0.0'),
 (0.005025339815246367, 'Q37_WEEKS_WORKED_2'),
 (0.004804839776878458, 'Q48_HISPANIC_1'),
 (0.004760160473891276, 'Q38_HOURS_WORKED_50.0'),
 (0.004701463393767443, 'Q2_COL_CREDIT_0.0'),
 (0.004645647217891493, 'Q40_BUSINESS_TYPE_16.0'),
 (0.00461382257562035, 'Q48_HISPANIC_2'),
 (0.004470672878719903, 'Q46_MARITAL_STATUS_3'),
 (0.004403949852284493, 'Q51_CITIZENSHIP_2.0'),
 (0.00439326089517504, 'Q4_HIGHEST_EDU_FOS_6.0'),
 (0.004326878924437552, 'Q37_WEEKS_WORKED_5'),
 (0.004297142216954953, 'Q49_RACE_02_1.0'),
 (0.0042251357167194655, 'Q49_RACE_04_1.0'),
 (0.004203940623384418, 'Q2_COL_CREDIT_3.0'),
 (0.00419887271354255, 'STRATUM1_1'),
 (0.004196081271843528, 'Q49_RACE_04_0.0'),
 (0.004102014555002187, 'Q49_RACE_02_0.0'),
 (0.004070216809357533, 'Q18_C_1'),
 (0.004037557122173168, 'STRATUM1_12'),
 (0.004016022056481424, 'Q18_C_2'),
 (0.003991484620411158, 'Q37_WEEKS_WORKED_4'),
 (0.00391574406266433, 'Q38_HOURS_WORKED_45.0'),
 (0.0038927999386046217, 'Q40_BUSINESS_TYPE_9.0'),
 (0.003866623614898884, 'STRATUM1_17'),
 (0.003860093739951801, 'Q40_BUSINESS_TYPE_14.0'),
 (0.0038465708224459526, 'Q8_ESL_1'),
 (0.003730019006466992, 'STRATUM1_18'),
 (0.0037198929341630423, 'STRATUM1_7'),
 (0.0036503677761382403, 'STRATUM1_9'),
 (0.0036365546679327588, 'Q40_BUSINESS_TYPE_13.0'),
 (0.003632278920781858, 'Q40_BUSINESS_TYPE_1.0'),
 (0.0035659599110623823, 'Q8_ESL_2'),
 (0.0035622822000212916, 'Q40_BUSINESS_TYPE_7.0'),
 (0.0035505611591960316, 'Q51_CITIZENSHIP_3.0'),
 (0.003485073785931777, 'Q49_RACE_06_1.0'),
 (0.0034493203391764314, 'Q38_HOURS_WORKED_20.0'),
 (0.0033772532518614477, 'Q38_HOURS_WORKED_35.0'),
 (0.003371763009967136, 'Q50_INTERNET_1.0'),
 (0.003338686541364429, 'Q50_INTERNET_2.0'),
 (0.0033270082499732684, 'Q49_RACE_06_0.0'),
 (0.0033200431212729474, 'Q4_HIGHEST_EDU_FOS_15.0'),
 (0.00328827129205522, 'Q1_HS_2'),
 (0.0032408172108210186, 'Q4_HIGHEST_EDU_FOS_11.0'),
 (0.0031668460761963948, 'Q4_HIGHEST_EDU_FOS_12.0'),
 (0.0031095217512728084, 'Q49_RACE_03_1.0'),
 (0.003063836431327566, 'Q4_HIGHEST_EDU_FOS_8.0'),
 (0.00306310542144754, 'Q4_HIGHEST_EDU_FOS_21.0'),
 (0.0030339780898064033, 'Q4_HIGHEST_EDU_FOS_2.0'),
 (0.0030279030292877807, 'Q16_CERT_LIC_CUR_JOB_3.0'),
 (0.0029956063368569985, 'Q49_RACE_03_0.0'),
 (0.0029197297269186614, 'Q2_COL_CREDIT_2.0'),
 (0.002871213045044823, 'STRATUM1_6'),
 (0.0028168398746246308, 'Q40_BUSINESS_TYPE_20.0'),
 (0.0027825970184563002, 'STRATUM1_4'),
 (0.0027571591661085843, 'Q40_BUSINESS_TYPE_10.0'),
 (0.0027509939576549603, 'Q38_HOURS_WORKED_60.0'),
 (0.0027194694008986497, 'Q38_HOURS_WORKED_30.0'),
 (0.0027047595412003815, 'Q1_HS_3'),
 (0.002622315352494857, 'Q4_HIGHEST_EDU_FOS_1.0'),
 (0.0026109093337133393, 'Q10_NUM_ACTIVE_1.0'),
 (0.0026089985109968962, 'Q40_BUSINESS_TYPE_17.0'),
 (0.002599357179465607, 'STRATUM1_11'),
 (0.0025616279167015206, 'Q40_BUSINESS_TYPE_4.0'),
 (0.002536888144314419, 'Q6_EDU_PLAN_2.0'),
 (0.002509902778641304, 'Q6_EDU_PLAN_0.0'),
 (0.0024904910351498852, 'Q5_COL_ENROLL_0'),
 (0.0024740300752739987, 'Q15_Q15_C_R_2.0'),
 (0.002472311451163907, 'Q7A_0.0'),
 (0.0024718133249479264, 'Q5_COL_ENROLL_3'),
 (0.0024023488803542937, 'STRATUM1_14'),
 (0.002388109453065313, 'Q44_MILITARY_1'),
 (0.002383169308221598, 'Q4_HIGHEST_EDU_FOS_22.0'),
 (0.0023208522286845635, 'Q14_CERT_LIC_REV_2.0'),
 (0.0023062204567701533, 'Q7_B_DEGREE_PLAN_FOS_0.0'),
 (0.0022988997653702334, 'Q17_C_3.0'),
 (0.0022580830338336964, 'Q15_Q15_C_R_1.0'),
 (0.002254595861034759, 'Q47_AGE_30'),
 (0.0022343706750498605, 'Q15_Q15_B_R_2.0'),
 (0.002190960885862915, 'Q4_HIGHEST_EDU_FOS_23.0'),
 (0.0021779764346761153, 'STRATUM1_16'),
 (0.002154600842635185, 'Q15_Q15_B_R_1.0'),
 (0.0021320547337972517, 'Q47_AGE_34'),
 (0.0021256323726445616, 'Q3_Q3_E_R_1.0'),
 (0.002111086345485025, 'Q3_Q3_D_R_0.0'),
 (0.002094056989275502, 'Q4_HIGHEST_EDU_FOS_18.0'),
 (0.002091187033854963, 'Q17_D_3.0'),
 (0.002079713639864286, 'Q3_Q3_D_R_1.0'),
 (0.00207913403144592, 'Q3_Q3_C_R_0.0'),
 (0.002074619450469321, 'Q3_Q3_B_R_1.0'),
 (0.002068455939750337, 'Q3_Q3_B_R_0.0'),
 (0.002066168495560681, 'Q47_AGE_35'),
 (0.0020567011437264767, 'Q3_Q3_A_R_0.0'),
 (0.0020378903480322117, 'Q47_AGE_26'),
 (0.002036547261335472, 'Q3_Q3_E_R_0.0'),
 (0.002036026048355236, 'Q47_AGE_25'),
 (0.0020334286044725505, 'Q47_AGE_28'),
 (0.0020269882990655293, 'Q15_Q15_A_R_2.0'),
 (0.002001064755364789, 'STRATUM1_8'),
 (0.0019614528520018656, 'Q3_Q3_A_R_1.0'),
 (0.0019465179429156078, 'Q3_Q3_C_R_1.0'),
 (0.0019095678082522568, 'Q47_AGE_32'),
 (0.0019051150986419418, 'STRATUM1_19'),
 (0.0019031944448048518, 'Q10_NUM_ACTIVE_2.0'),
 (0.001890065451971606, 'Q47_AGE_42'),
 (0.0018452669231593841, 'Q47_AGE_24'),
 (0.0018450560515824294, 'Q47_AGE_33'),
 (0.0018410068495139315, 'Q47_AGE_56'),
 (0.0018362901113859057, 'Q47_AGE_29'),
 (0.0018359375216475222, 'Q47_AGE_36'),
 (0.0018354441901046918, 'Q47_AGE_27'),
 (0.001834533055060853, 'Q47_AGE_37'),
 (0.0018205242360181042, 'Q47_AGE_50'),
 (0.0018187331669321013, 'Q47_AGE_53'),
 (0.001802673655924768, 'Q17_B_3.0'),
 (0.0017983320723589486, 'Q47_AGE_39'),
 (0.0017980533830917814, 'Q47_AGE_40'),
 (0.0017972656930446828, 'Q17_D_2.0'),
 (0.001772320107188498, 'Q5_COL_ENROLL_2'),
 (0.0017560258559056136, 'Q15_Q15_A_R_1.0'),
 (0.001753901393344992, 'Q47_AGE_58'),
 (0.0017202078722724572, 'Q11_MOST_IMP_CERT_LIC_1.0'),
 (0.001714503118148416, 'Q44_MILITARY_4'),
 (0.0017135227562683438, 'Q13_CERT_LIC_REQ_2.0'),
 (0.0017099010099599398, 'Q47_AGE_61'),
 (0.0017058271616626876, 'Q47_AGE_31'),
 (0.001704236836251245, 'Q47_AGE_47'),
 (0.001678123025249706, 'Q12_CERT_LIC_WORK_8.0'),
 (0.001671739356982668, 'Q4_HIGHEST_EDU_FOS_19.0'),
 (0.0016655820481581121, 'Q7A_3.0'),
 (0.0016542523171906728, 'Q47_AGE_52'),
 (0.0016388322300679998, 'Q47_AGE_46'),
 (0.0016363910161240028, 'Q4_HIGHEST_EDU_FOS_16.0'),
 (0.0016090401099092277, 'Q47_AGE_55'),
 (0.0016054247632337217, 'Q47_AGE_64'),
 (0.0015991445642099377, 'Q47_AGE_48'),
 (0.0015929840950666043, 'Q38_HOURS_WORKED_25.0'),
 (0.0015499627880338615, 'Q47_AGE_54'),
 (0.0015487466335171876, 'Q4_HIGHEST_EDU_FOS_14.0'),
 (0.0015440389024984375, 'Q17_A_3.0'),
 (0.0015410261012057493, 'Q47_AGE_62'),
 (0.0015376378240130396, 'STRATUM1_3'),
 (0.0015298204072488133, 'Q40_BUSINESS_TYPE_2.0'),
 (0.0015257484932969024, 'Q47_AGE_43'),
 (0.0015204123594494904, 'Q47_AGE_23'),
 (0.0015080318334910652, 'STRATUM1_13'),
 (0.0014787013632350827, 'Q27_APP_1'),
 (0.0014752484374341152, 'Q22_CERTIFICATE_ENROLL_3.0'),
 (0.0014709611644744803, 'Q11_MOST_IMP_CERT_LIC_7.0'),
 (0.0014677501469696228, 'Q47_AGE_60'),
 (0.001466623058811131, 'Q47_AGE_57'),
 (0.0014575103931187944, 'Q18_D_SPECIFY_1.0'),
 (0.0014541197110230623, 'Q47_AGE_45'),
 (0.0014504590948374455, 'Q1_HS_1'),
 (0.00144794228934333, 'Q47_AGE_51'),
 (0.0014443046639712567, 'Q46_MARITAL_STATUS_4'),
 (0.001434938761041403, 'Q40_BUSINESS_TYPE_12.0'),
 (0.0014211921337087825, 'Q4_HIGHEST_EDU_FOS_7.0'),
 (0.0014153402552629882, 'Q14_CERT_LIC_REV_1.0'),
 (0.0014028258748497524, 'Q47_AGE_44'),
 (0.0013825114941770405, 'Q23_CERTIFCATE_CREDITS_2.0'),
 (0.0013727042777261003, 'Q47_AGE_41'),
 (0.0013721172313625263, 'Q38_HOURS_WORKED_55.0'),
 (0.0013718371191705702, 'Q12_CERT_LIC_WORK_6.0'),
 (0.0013530949781448323, 'Q47_AGE_59'),
 (0.0013504916941805794, 'Q47_AGE_63'),
 (0.001348488211112747, 'Q14_CERT_LIC_REV_3.0'),
 (0.001347136975390526, 'Q18_D_1'),
 (0.0013246602251212455, 'Q47_AGE_49'),
 (0.00131231543713569, 'Q11_MOST_IMP_CERT_LIC_5.0'),
 (0.00130438742038917, 'Q24_CERTIFICATE_TRAIN_2.0'),
 (0.0012973269516748504, 'Q11_MOST_IMP_CERT_LIC_0.0'),
 (0.0012798362246584265, 'Q26_C_3.0'),
 (0.001253450628894656, 'Q26_B_0.0'),
 (0.0012395644682706495, 'Q18_D_2'),
 (0.0012395584767918937, 'Q13_CERT_LIC_REQ_1.0'),
 (0.0012342218345081236, 'Q18_D_SPECIFY_0.0'),
 (0.0012251332669038816, 'Q22_CERTIFICATE_ENROLL_0.0'),
 (0.0012209819836170664, 'Q23_CERTIFCATE_CREDITS_0.0'),
 (0.0012144533340811437, 'Q25_CERTIFICATE_JOB_0.0'),
 (0.0012135666959491019, 'Q38_HOURS_WORKED_37.0'),
 (0.0011995008769028512, 'LANG_1'),
 (0.001193067616847685, 'Q26_A_0.0'),
 (0.0011883763265225702, 'Q7A_4.0'),
 (0.0011717984678960925, 'Q21_CERTIFICATE_HOURS_0.0'),
 (0.0011699441730306358, 'Q26_C_0.0'),
 (0.0011680477938691648, 'LANG_2'),
 (0.0011637433577742127, 'Q40_BUSINESS_TYPE_5.0'),
 (0.0011600232129704263, 'Q47_AGE_22'),
 (0.001148588049570228, 'Q17_B_2.0'),
 (0.0011435035858834506, 'Q19_CERTIFICATE_FOS_0.0'),
 (0.0011413542209774922, 'Q24_CERTIFICATE_TRAIN_0.0'),
 (0.0011172724396266208, 'Q17_D_1.0'),
 (0.0011084781749057984, 'Q47_AGE_38'),
 (0.0011007484211667188, 'Q24_CERTIFICATE_TRAIN_1.0'),
 (0.001086944681917025, 'Q25_CERTIFICATE_JOB_2.0'),
 (0.0010864291160303933, 'Q16_CERT_LIC_CUR_JOB_2.0'),
 (0.001079990470782384, 'Q12_CERT_LIC_WORK_13.0'),
 (0.001076542396705584, 'Q26_A_2.0'),
 (0.0010761589578716004, 'Q26_B_1.0'),
 (0.0010716428734517682, 'Q16_CERT_LIC_CUR_JOB_1.0'),
 (0.0010716319501769937, 'Q25_CERTIFICATE_JOB_4.0'),
 (0.0010537923246143402, 'Q21_CERTIFICATE_HOURS_1.0'),
 (0.001053416555229862, 'Q38_HOURS_WORKED_38.0'),
 (0.0010529358928224137, 'Q38_HOURS_WORKED_42.0'),
 (0.0010490710681086044, 'Q26_A_3.0'),
 (0.0010364404507613766, 'Q46_MARITAL_STATUS_2'),
 (0.0010324551706563927, 'Q7_B_DEGREE_PLAN_FOS_15.0'),
 (0.0010217745755170358, 'Q40_BUSINESS_TYPE_3.0'),
 (0.0010174561160617372, 'Q12_CERT_LIC_WORK_0.0'),
 (0.0010007116213835425, 'Q26_C_2.0'),
 (0.0009948661439433794, 'Q17_C_2.0'),
 (0.0009871142236589027, 'Q10_NUM_ACTIVE_3.0'),
 (0.0009862938328766818, 'Q23_CERTIFCATE_CREDITS_1.0'),
 (0.0009810124723364042, 'Q27_APP_2'),
 (0.0009754259393750515, 'Q17_A_2.0'),
 (0.0009732977071055344, 'Q38_HOURS_WORKED_32.0'),
 (0.0009709079617767264, 'Q28_APP_WORK_6.0'),
 (0.00096887269248284, 'Q21_CERTIFICATE_HOURS_4.0'),
 (0.0009635906562406025, 'Q29_Q29_C_R_1.0'),
 (0.0009617279838156047, 'Q15_Q15_A_R_0.0'),
 (0.000958698980193034, 'Q25_CERTIFICATE_JOB_3.0'),
 (0.0009510785411530738, 'Q44_MILITARY_2'),
 (0.0009389128531576189, 'Q38_HOURS_WORKED_8.0'),
 (0.0009383053738318172, 'Q47_AGE_20'),
 (0.0009365632531950145, 'Q29_Q29_A_R_2.0'),
 (0.000930698521518085, 'Q34_C_3.0'),
 (0.0009204188730512458, 'Q26_B_3.0'),
 (0.0009185085064411396, 'Q16_CERT_LIC_CUR_JOB_0.0'),
 (0.0009162141367846867, 'Q31_APP_CERTIFICATE_0.0'),
 (0.0009120694233948593, 'Q17_A_0.0'),
 (0.0009096948389499035, 'Q26_B_2.0'),
 (0.0009087252474802471, 'Q7A_6.0'),
 (0.0009060004385265999, 'Q29_Q29_E_R_2.0'),
 (0.0008993282577283431, 'Q17_D_0.0'),
 (0.0008953468753826619, 'Q29_Q29_D_R_1.0'),
 (0.0008885023778822859, 'Q17_C_0.0'),
 (0.0008814692693845228, 'Q19_CERTIFICATE_FOS_14.0'),
 (0.0008760579716578707, 'Q29_Q29_B_R_1.0'),
 (0.0008743938239859276, 'Q4_HIGHEST_EDU_FOS_17.0'),
 (0.0008721482669304512, 'Q31_APP_CERTIFICATE_1.0'),
 (0.0008706663731429695, 'Q15_Q15_B_R_0.0'),
 (0.0008550917838956808, 'Q15_Q15_C_R_0.0'),
 (0.000849205893480155, 'Q27_APP_3'),
 (0.0008483939368551037, 'Q22_CERTIFICATE_ENROLL_4.0'),
 (0.0008476228417330893, 'Q34_B_0.0'),
 (0.0008406542516341764, 'Q9_CERT_LIC_0'),
 (0.0008385312068883423, 'Q32_APP_JOB_4.0'),
 (0.0008333050082659518, 'Q30_APP_CERT_LIC_2.0'),
 (0.0008327821164772406, 'Q34_C_0.0'),
 (0.0008316607225722941, 'Q33_APP_SKILL_USE_4.0'),
 (0.0008258493935602725, 'Q38_HOURS_WORKED_36.0'),
 (0.0008238896752767331, 'Q32_APP_JOB_0.0'),
 (0.000823253858635549, 'Q38_HOURS_WORKED_24.0'),
 (0.0008164214216564294, 'Q33_APP_SKILL_USE_0.0'),
 (0.0008158521317338772, 'Q4_HIGHEST_EDU_FOS_5.0'),
 (0.0008009809474922099, 'Q29_Q29_B_R_0.0'),
 (0.0008009390146896142, 'Q47_AGE_21'),
 (0.0007951553143689249, 'Q49_RACE_05_1.0'),
 (0.000795058579190104, 'Q18_D_SPECIFY_2.0'),
 (0.0007920717958057437, 'Q28_APP_WORK_0.0'),
 (0.0007913103600720689, 'Q17_B_0.0'),
 (0.0007906246665724268, 'Q29_Q29_E_R_0.0'),
 (0.0007889008956985433, 'Q29_Q29_A_R_0.0'),
 (0.0007867825695966152, 'Q4_HIGHEST_EDU_FOS_3.0'),
 (0.000783675561316589, 'Q30_APP_CERT_LIC_0.0'),
 (0.0007800767470097253, 'Q34_A_3.0'),
 (0.0007790745167999931, 'Q11_MOST_IMP_CERT_LIC_9.0'),
 (0.0007780429708195437, 'Q34_A_0.0'),
 (0.000768124440624592, 'Q29_Q29_C_R_0.0'),
 (0.0007647007614257442, 'Q10_NUM_ACTIVE_0.0'),
 (0.0007645987388666135, 'Q38_HOURS_WORKED_10.0'),
 (0.000764418328391077, 'Q38_HOURS_WORKED_15.0'),
 (0.000762059416790185, 'Q14_CERT_LIC_REV_0.0'),
 (0.0007536434170572833, 'Q9_CERT_LIC_1'),
 (0.0007524405238755527, 'Q13_CERT_LIC_REQ_0.0'),
 (0.0007509407561298066, 'Q26_A_1.0'),
 (0.0007500178611228836, 'Q38_HOURS_WORKED_48.0'),
 (0.0007480448554624305, 'Q34_B_3.0'),
 (0.0007450801849523404, 'Q21_CERTIFICATE_HOURS_3.0'),
 (0.000736138854659814, 'Q40_BUSINESS_TYPE_15.0'),
 (0.0007357144761917923, 'Q29_Q29_B_R_2.0'),
 (0.0007329403006147606, 'Q38_HOURS_WORKED_65.0'),
 (0.0007323684802401556, 'Q40_BUSINESS_TYPE_11.0'),
 (0.0007227344692587321, 'Q31_APP_CERTIFICATE_2.0'),
 (0.0007214619628437588, 'Q4_HIGHEST_EDU_FOS_13.0'),
 (0.0007191995340568311, 'Q29_Q29_D_R_0.0'),
 (0.0006830432785912625, 'Q11_MOST_IMP_CERT_LIC_6.0'),
 (0.0006808716985739909, 'Q7_B_DEGREE_PLAN_FOS_6.0'),
 (0.0006784365050474944, 'Q11_MOST_IMP_CERT_LIC_12.0'),
 (0.0006698363535494056, 'Q47_AGE_18'),
 (0.0006687354341332487, 'Q29_Q29_E_R_1.0'),
 (0.0006684697531450652, 'Q49_RACE_05_0.0'),
 (0.0006609768698173853, 'Q38_HOURS_WORKED_44.0'),
 (0.000659904334942001, 'Q13_CERT_LIC_REQ_3.0'),
 (0.0006567200690462941, 'Q34_A_2.0'),
 (0.0006555585459824043, 'Q30_APP_CERT_LIC_1.0'),
 (0.0006406608417113522, 'Q10_NUM_ACTIVE_4.0'),
 (0.000638088993300586, 'Q33_APP_SKILL_USE_3.0'),
 (0.0006371260268978994, 'Q7A_2.0'),
 (0.0006370654278204292, 'Q17_C_1.0'),
 (0.0006278213791822469, 'Q47_AGE_19'),
 (0.0006264476472855799, 'Q40_BUSINESS_TYPE_18.0'),
 (0.0006155321363769435, 'Q25_CERTIFICATE_JOB_1.0'),
 (0.0006152267978588418, 'Q4_HIGHEST_EDU_FOS_9.0'),
 (0.0006131738846504541, 'Q6_EDU_PLAN_1.0'),
 (0.0006095758527209245, 'Q12_CERT_LIC_WORK_7.0'),
 (0.0006093464436232248, 'Q22_CERTIFICATE_ENROLL_2.0'),
 (0.0006048845018174356, 'Q17_A_1.0'),
 (0.0005974020225958782, 'Q7A_1.0'),
 (0.000591646933490725, 'Q26_C_1.0'),
 (0.0005914421236740397, 'Q7_B_DEGREE_PLAN_FOS_21.0'),
 (0.000569942942990839, 'Q32_APP_JOB_3.0'),
 (0.0005684312872305346, 'Q17_B_1.0'),
 (0.0005677568843327087, 'Q34_B_2.0'),
 (0.0005654991195336406, 'Q11_MOST_IMP_CERT_LIC_10.0'),
 (0.0005652790373029462, 'Q32_APP_JOB_2.0'),
 (0.0005646592549116145, 'STRATUM1_10'),
 (0.0005644090543222792, 'STRATUM1_15'),
 (0.0005505185237348984, 'STRATUM1_20'),
 (0.0005340983743473123, 'Q40_BUSINESS_TYPE_21.0'),
 (0.0005154444067258524, 'Q4_HIGHEST_EDU_FOS_20.0'),
 (0.0005142824801132142, 'Q11_MOST_IMP_CERT_LIC_2.0'),
 (0.0005142252294290518, 'Q11_MOST_IMP_CERT_LIC_8.0'),
 (0.0005142154275137792, 'Q11_MOST_IMP_CERT_LIC_15.0'),
 (0.000509081537509661, 'Q38_HOURS_WORKED_12.0'),
 (0.0005054691703379982, 'Q34_C_2.0'),
 (0.0005028653309482418, 'Q4_HIGHEST_EDU_FOS_4.0'),
 (0.0004905090687475279, 'Q12_CERT_LIC_WORK_9.0'),
 (0.0004886485534186446, 'Q34_B_1.0'),
 (0.00048695424938104614, 'Q21_CERTIFICATE_HOURS_2.0'),
 (0.0004683208792909163, 'Q38_HOURS_WORKED_80.0'),
 (0.00046159248352507293, 'Q12_CERT_LIC_WORK_12.0'),
 (0.0004614988151052625, 'Q38_HOURS_WORKED_5.0'),
 (0.0004601976704734397, 'Q7_B_DEGREE_PLAN_FOS_8.0'),
 (0.00045560125139606903, 'Q38_HOURS_WORKED_43.0'),
 (0.00045078097866105364, 'Q21_CERTIFICATE_HOURS_5.0'),
 (0.0004505459478495435, 'Q29_Q29_C_R_2.0'),
 (0.00045041070910068555, 'Q29_Q29_A_R_1.0'),
 (0.00044117938545469327, 'Q11_MOST_IMP_CERT_LIC_18.0'),
 (0.0004402114060767393, 'Q7_B_DEGREE_PLAN_FOS_11.0'),
 (0.00043041145395837464, 'Q7_B_DEGREE_PLAN_FOS_22.0'),
 (0.00042844795426416144, 'Q12_CERT_LIC_WORK_14.0'),
 (0.00041703418193905274, 'Q7_B_DEGREE_PLAN_FOS_12.0'),
 (0.0004137939725292205, 'Q19_CERTIFICATE_FOS_6.0'),
 (0.00041068512505453345, 'Q12_CERT_LIC_WORK_2.0'),
 (0.0004006920309058718, 'Q19_CERTIFICATE_FOS_5.0'),
 (0.00039754828033463177, 'Q38_HOURS_WORKED_16.0'),
 (0.00039535974157549775, 'Q12_CERT_LIC_WORK_15.0'),
 (0.00038799928605182853, 'Q38_HOURS_WORKED_28.0'),
 (0.00038709232532832994, 'Q38_HOURS_WORKED_70.0'),
 (0.0003706402275530936, 'STRATUM1_5'),
 (0.0003455640395082997, 'Q33_APP_SKILL_USE_2.0'),
 (0.0003452114530474546, 'Q12_CERT_LIC_WORK_17.0'),
 (0.00034494767347545695, 'Q28_APP_WORK_5.0'),
 (0.000342725680907232, 'Q8_ESL_-3'),
 (0.00034220936319810874, 'Q38_HOURS_WORKED_46.0'),
 (0.0003386175658737954, 'Q38_HOURS_WORKED_6.0'),
 (0.00033596250322164673, 'Q7_B_DEGREE_PLAN_FOS_2.0'),
 (0.00033254917894007236, 'Q11_MOST_IMP_CERT_LIC_19.0'),
 (0.00033062733635054936, 'Q11_MOST_IMP_CERT_LIC_3.0'),
 (0.0003210372400221241, 'Q11_MOST_IMP_CERT_LIC_14.0'),
 (0.00031932109181464087, 'Q12_CERT_LIC_WORK_1.0'),
 (0.00031261406072961, 'Q28_APP_WORK_1.0'),
 (0.00030594065723821463, 'Q38_HOURS_WORKED_27.0'),
 (0.00030351998342211217, 'Q7_B_DEGREE_PLAN_FOS_23.0'),
 (0.00029627264961854677, 'Q38_HOURS_WORKED_7.0'),
 (0.0002931409716093414, 'Q18_D_SPECIFY_3.0'),
 (0.000289088076587625, 'Q28_APP_WORK_2.0'),
 (0.0002866283688012174, 'Q19_CERTIFICATE_FOS_10.0'),
 (0.00028465271609402206, 'Q11_MOST_IMP_CERT_LIC_20.0'),
 (0.0002842560280874962, 'Q17_B_4.0'),
 (0.0002835265343848668, 'Q17_A_4.0'),
 (0.0002804566348198767, 'Q10_NUM_ACTIVE_5.0'),
 (0.00027716672532064715, 'Q38_HOURS_WORKED_52.0'),
 (0.00027597048660432124, 'Q29_Q29_D_R_2.0'),
 (0.00027323050298324605, 'Q12_CERT_LIC_WORK_4.0'),
 (0.0002709584693071931, 'Q7A_5.0'),
 (0.0002646003235241727, 'Q32_APP_JOB_1.0'),
 (0.00025781793013514916, 'Q19_CERTIFICATE_FOS_1.0'),
 (0.00025417917824327387, 'Q34_A_1.0'),
 (0.0002530844409820263, 'Q40_BUSINESS_TYPE_19.0'),
 (0.00025156754198761864, 'Q4_HIGHEST_EDU_FOS_26.0'),
 (0.00024881848699735893, 'Q19_CERTIFICATE_FOS_2.0'),
 (0.00024342768607587883, 'Q38_HOURS_WORKED_22.0'),
 (0.00024154131674729415, 'Q38_HOURS_WORKED_4.0'),
 (0.00024136499059100098, 'Q33_APP_SKILL_USE_1.0'),
 (0.00023847745109357185, 'Q37_WEEKS_WORKED_-3'),
 (0.00023539905187084154, 'Q22_CERTIFICATE_ENROLL_1.0'),
 (0.00023427697092876982, 'Q7_B_DEGREE_PLAN_FOS_19.0'),
 (0.00021650305665175119, 'Q38_HOURS_WORKED_47.0'),
 (0.00021260692361504713, 'Q15_D_SPECIFY_FLAG_1'),
 (0.000208435331125691, 'Q38_HOURS_WORKED_34.0'),
 (0.00020496093556880118, 'Q17_C_4.0'),
 (0.00020491868289887653, 'Q26_B_4.0'),
 (0.00020230125567590902, 'Q38_HOURS_WORKED_18.0'),
 (0.00019857942270180167, 'Q18_C_-3'),
 (0.00019404227286249183, 'Q19_CERTIFICATE_FOS_11.0'),
 (0.00018992847947498778, 'Q12_CERT_LIC_WORK_3.0'),
 (0.0001837385032724132, 'Q38_HOURS_WORKED_9.0'),